export {
  default as TextInput,
  UNDERLINE_FROM_CENTER as TEXT_INPUT_UNDERLINE_FROM_CENTER,
  UNDERLINE_FROM_LEFT as TEXT_INPUT_UNDERLINE_FROM_LEFT,
  UNDERLINE_NONE as TEXT_INPUT_UNDERLINE_NONE,
} from './input/TextInput';